//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Random_NewtonJson
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using DeterRandom.Seeds;
using Newtonsoft.Json;
using System;
using System.Collections.Concurrent;

namespace DeterRandom;

//public static RandomSm64 Shared = RandomSm64.CreateFromPreSeed(42);
[JsonConverter(typeof(NewtonJson_RandomSm64))]
public sealed partial class RandomSm64
{
    //Thread safe implemenatation with pool(bag) for temp json objects
    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    private class NewtonJson_RandomSm64 : JsonConverter<RandomSm64>
    {
        //to check that no memory leaks change this class and static field to internal and uncomment counter in AfterEveryTest() in test project.
        private static readonly ConcurrentBag<NewtonJson_RandomSm64> s_pool = new ConcurrentBag<NewtonJson_RandomSm64>();
        [JsonRequired]
        public SplitMix64 initialSeed;
        [JsonProperty(Required = Required.Default)]
        public SplitMix64? current;
        private static NewtonJson_RandomSm64 FromPool()
        {
            NewtonJson_RandomSm64 o;
            if (s_pool.TryTake(out o) == false)
                o = new NewtonJson_RandomSm64();
            //if (o.current.HasValue)
            o.current = null;
            return o;
        }
        public override void WriteJson(JsonWriter writer, RandomSm64 value, JsonSerializer serializer)
        {
            NewtonJson_RandomSm64 o = FromPool();
            unchecked
            {
                o.initialSeed = value._initialSeed;
                o.current = value._seed;
            }
            serializer.Serialize(writer, o);
            s_pool.Add(o);
        }

        public override RandomSm64 ReadJson(JsonReader reader, Type objectType, RandomSm64 existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            NewtonJson_RandomSm64 o = FromPool();
            serializer.Populate(reader, o);
            RandomSm64 result;
            if (o.current.HasValue)
                result = new RandomSm64(o.initialSeed, o.current.Value);
            else
                result = new RandomSm64(o.initialSeed);
            s_pool.Add(o);
            return result;
        }
    }
}

